openapi: 3.0.0
info:
  title: Runscope API
  description: Manage Runscope programmatically.
  version: 1.0.0
servers:
  - url: 'https://api.runscope.com/'
security:
  - runscope_auth:
      - 'api:read'
