get:
  summary: >-
    Return details of the test's environments (only those that belong to the
    specified test)
  tags:
    - Test Environments
  parameters:
    - $ref: '#/components/parameters/bucketKey'
    - $ref: '#/components/parameters/testId'
  responses:
    '200':
      description: List of environments belonging to this test.
      content:
        application/json:
          schema:
            properties:
              data:
                type: array
                items:
                  $ref: '#/components/schemas/Environment'
              meta:
                $ref: '#/components/schemas/Meta'
            type: object
  security:
    - runscope_auth:
        - 'api:read'
        - 'test:read'
post:
  summary: Create new test environment.
  tags:
    - Test Environments
  parameters:
    - $ref: '#/components/parameters/bucketKey'
    - $ref: '#/components/parameters/testId'
  responses:
    '201':
      description: Details of the new test environment.
  security:
    - runscope_auth:
        - 'api:read'
        - 'test:write'
  requestBody:
    $ref: '#/components/requestBodies/Environment'
